### ISSUE TITLE
Support zero copy using the bytes crate

### ISSUE THREAD

**Issue by dignifiedquire** [quininer/cbor4ii#25]
I have a few cases where I would like to deserialize cbor from an incoming `BytesMut` into cbor struct that looks sth like this

```rust
struct Foo {
   pub data: Bytes,
   // other small fields
}
```

where I very much need to avoid copying the data (that data is on the order of 100s of MB often).

I tried hacking sth together, but didn't quite get anywhere, so wondering if you could give me some hints on how this could be done. Thanks.

**Comment by bdbai** [comment]
Please take a look at [serde_bytes](https://github.com/serde-rs/bytes).

**Comment by dignifiedquire** [comment]
@bdbai I don’t understand how serde_bytes would be useful here. The bytes crate is using refcounted slices under the hood, which is sth very different

**Comment by quininer** [comment]
You can do this manually, like

```rust
#[derive(Deserialize)]
struct Foo<'a> {
    #[serde(with = "serde_bytes")]
    pub data: &'a [u8]
}

let bytes: Bytes = get_bytes();
let foo: Foo<'_> = from_slice(&bytes).unwrap();
let data: Bytes = bytes.slice_ref(foo.data);
```

The trick is to use the [Bytes::slice_ref](https://docs.rs/bytes/latest/bytes/struct.Bytes.html#method.slice_ref) method.

**Comment by dignifiedquire** [comment]
Thanks, that works, a little cumbersome with nested types, but it does work.
