### ISSUE TITLE
Error parsing F16 - Core(Mismatch { name: "f16", found: 60 })

### ISSUE THREAD

**Issue by brusshamilton** [quininer/cbor4ii#29]
I'm using calling `deserialize_any` with a custom visitor and I noticed that I get the `Core(Mismatch { name: "f16", found: 60 })` error whenever I have a 16 bit float in the encoded string (in this case 1.0, which is encoded as 3C 00).

I have narrowed this down to a line in `serde/de.rs:93`:
```rust
marker::F16 => {
  de.reader.advance(1);
  let v = half::f16::decode(&mut de.reader)?;
  visitor.visit_f32(v.into())
},
```
I think the `de.reader.advance(1);` should not be there, since the decode method checks the major type again and errors out if it doesn't match. When I comment that line out, the parser works as expected.

**Comment by quininer** [comment]
You're right, would you like to open a PR?

**Comment by brusshamilton** [comment]
Created pull request #31.

**Comment by quininer** [comment]
0.3.3 has been released

**Comment by quininer** [comment]
done
