### ISSUE TITLE
Should this work?

### ISSUE THREAD

**Issue by smoelius** [quininer/cbor4ii#4]
```rust
use serde::{Deserialize, Serialize};

#[derive(Deserialize, Serialize)]
enum Foo {
    A(String),
}

fn main() {
    let foo = Foo::A(String::new());

    let mut data = Vec::new();
    cbor4ii::serde::to_writer(&mut data, &foo).unwrap();

    let reader = std::io::BufReader::new(data.as_slice());
    let _: Foo = cbor4ii::serde::from_reader(reader).unwrap();
}
```
I get:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: RequireBorrowed { name: "str" }', src/main.rs:15:54
```
Can you tell me what am I doing wrong?

**Comment by quininer** [comment]
Oh, the `deserialize_str` behavior of serde is a bit hard to understand. I will fix it immediately.

**Comment by quininer** [comment]
Oh, the `deserialize_str` behavior of serde is a bit hard to understand. I will fix it immediately.

**Comment by smoelius** [comment]
Thanks for the prompt reply.

**Comment by quininer** [comment]
I think this is like a bug in serde handling of enum, because the `String` type should obviously call `deserialize_string` to benefit from the owned type. but this is not a strong agreement, so `cbor4ii` should not rely on it.
