### ISSUE TITLE
Error refactor

### ISSUE THREAD

**Issue by quininer** [quininer/cbor4ii#9]
Error seems a bit confusing now, especially `DecodeError`.

* Split `core::Error` and `serde::Error` so that you don't care about `Msg` kind when using `core` mod.
* Merge kinds such as `Eof`/`RequireLength`, `Mismatch`/`TypeMismatch`, etc.

Since this affects the api, it will be in the next version.

**Comment by vmx** [comment]
It might be quicker for you to do it yourself. But if it would help you, I could provide a PR if you give a detailed version of what the new errors should look like. I'm interested in this, as I currently have a 1:1 mapping in my code to your errors and such a simplification would be welcome.

**Comment by quininer** [comment]
@vmx I haven't figured out what it should look like yet, feel free to open a PR if you have a good idea. :D
